# Generated by Django 4.2.3 on 2024-04-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
